### ISSUE TITLE
App is not working in Samsung, htc mobile 

### ISSUE THREAD

**Issue by TausifUddinAhmed** [TuyaInc/tuyasmart_android_sdk#11]
I have tried to run this sdk in samsung mobile. When i  want to log into the account by giving correct credentials, the following error is shown
` Process: com.tuya.smart.sdk.demo, PID: 22123
    java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.tuya.smart.sdk.demo-2/base.apk)
        at com.tuya.smart.android.common.utils.NotificationHelper$Builder.build(NotificationHelper.java:194)
        at com.tuya.smart.sdk.constant.ServiceNotification.<init>(ServiceNotification.java:27)
        at com.tuya.smart.sdk.constant.ServiceNotification.<clinit>(ServiceNotification.java:15)
        at com.tuya.smart.sdk.constant.ServiceNotification.getInstance(ServiceNotification.java:31)
        at com.tuya.smart.security.device.MqttModel.<init>(MqttModel.java:109)
        at com.tuya.smart.security.device.MqttModel.a(MqttModel.java:93)
        at com.tuya.smart.android.device.TuyaSmartDevice.initMqtt(TuyaSmartDevice.java:133)
        at com.tuya.smart.android.device.TuyaSmartDevice.getInstance(TuyaSmartDevice.java:174)
        at com.tuya.smart.android.user.model.BaseLoginModel.loginSuccess(BaseLoginModel.java:60)
        at com.tuya.smart.android.user.model.LoginWithUsernameModel$1$1.onSuccess(LoginWithUsernameModel.java:118)
        at com.tuya.smart.android.user.model.LoginWithUsernameModel$1$1.onSuccess(LoginWithUsernameModel.java:108)
        at com.tuya.smart.android.network.Business$RequestTask$2.run(Business.java:435)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

How to solve this problem ? thanks in advance :)

**Comment by NextApp** [comment]
pls  update the Targetsdk version to the 27+.
and update the appcompat-v7 to 27.1.1+
